### ISSUE TITLE
How do I use docchi once it generates the JSON?

### ISSUE THREAD

**Issue by sunjay** [daliwali/docchi#11]
Once docchi has generated its JSON, how can I turn that into HTML documentation?

You say that it's generated in a JSDoc format, but (as far as I can tell) JSDoc doesn't provide anything to read what docchi outputs.

Could you help me out? This might be a great thing to put in the README
Thanks

**Comment by daliwali** [comment]
Docchi accepts JSDoc as an input format, meaning that by default it parses JSDoc comments. The output is simply JSON, and it's up to you how to display it. The functionality is similar to [dox](https://github.com/tj/dox), except that it works by traversing the AST rather than using regexes, so it can match contexts where dox can't.
