### ISSUE TITLE
Property assignments not providing context

### ISSUE THREAD

**Issue by djMax** [daliwali/docchi#7]
This is basically a rehash of the previous issue with a new twist. I had to split up my file because docchi was not understanding classes as properties, like

````
Invoice.Item = class {
}
````

It would pick up the class, but not any methods or constructors in it. And when it did pick up things, the target was basically a dotted list of the other classes it had found in the file even though these were not inner classes. So I figured single entity per file was better anyways, but then my enums stopped working somehow:

````
/**
 * Valid invoice statuses
 * @enum {number}
 */
var InvoiceStatus = {
    /**
     * The invoice has not been saved to the server
     */
    NEW: 0
};
````

The second comment there gets picked up with no context and without the "NEW" information.

**Comment by daliwali** [comment]
I can add support for this, but I want to ask why you opt to use anonymous classes? Wouldn't this be equivalent:

```js
class Item { ... }
Invoice.Item = Item;
```

**Comment by djMax** [comment]
You can't do enums that way. The class syntax does not allow "fields," only methods right?

**Comment by djMax** [comment]
I found a workaround for now which is that if I assign the enum to a "real class" property, it gets picked up fine. So 

```
class Invoice {
}
Invoice.Status = {
    NEW: 0
}
````

works.

**Comment by daliwali** [comment]
I pushed `0.6.0`, which changes some behavior regarding classes. It now picks up unnamed classes, but your unnamed class methods won't get a target. 

Assigning static properties to a class is external to the class syntax, you would have to do `Class.property = 'foo'` outside of the class body.

The reason why it didn't pick up on `var obj = { ... }` is because it doesn't get variable assignment yet, which sounds like it should be something simple to do, it'll be done later.

**Comment by daliwali** [comment]
Now there is support for variable assignment in `0.7.0`, so all of the problems in your original issue should be resolved.

**Comment by djMax** [comment]
You're a machine!
