### ISSUE TITLE
Purpose of Docchi?

### ISSUE THREAD

**Issue by balupton** [daliwali/docchi#8]
If I understand correctly, Docchi exists to solve things like https://github.com/yui/yuidoc/issues/336 correct?

**Comment by daliwali** [comment]
It was inspired by `dox` which I used to use, which does the same things: parse comments, match comments to source node, and provide output useful for generating HTML documentation from a template. There are two key differences:

- docchi can be customized to parse any kind of comment, not just JSDoc, but JSDoc is still a sensible default.
- docchi uses AST traversal instead of regular expressions. for example, this is what makes it possible to reference a class method comment to its class (if it used regexes, that would be much more difficult, and is not supported by dox).

why use docchi instead of official jsdoc?

- it's vastly more lightweight, but it doesn't come with certain features like HTML output.
- it understands ES6 syntax. jsdoc uses the esprima parser which doesn't have es6 support yet.
